
drop table if exists TROLE;

CREATE TABLE TROLE (
	C_ROLEID VARCHAR(100),
	C_ROLECODE VARCHAR(100),
	C_ROLENAME VARCHAR(100),
	C_ROLEDESC VARCHAR(100),
	C_CREATEDBYID VARCHAR(100),
	D_CREATEDTIME DATE,
	C_LASTMODIFIEDBYID VARCHAR(100),
	D_LASTMODIFIEDTIME DATE
);
