
drop table if exists TROLEPRIVILEGERELATION;

CREATE TABLE TROLEPRIVILEGERELATION (
	C_ROLEPRIVILEGERELATIONID VARCHAR(100),
	C_ROLECODE VARCHAR(100),
	C_PRIVILEGEFULLCODE VARCHAR(100),
	C_ISDELETED VARCHAR(1),
	C_CREATEDBYID VARCHAR(100),
	D_CREATEDTIME DATE,
	C_LASTMODIFIEDBYID VARCHAR(100),
	D_LASTMODIFIEDTIME DATE
);
