
drop table if exists TUSERROLERELATION;

CREATE TABLE TUSERROLERELATION (
	C_USERROLERELATIONID VARCHAR(100),
	C_USERCODE VARCHAR(100),
	C_ROLECODE VARCHAR(100),
	C_CREATEDBYID VARCHAR(100),
	D_CREATEDTIME DATE,
	C_LASTMODIFIEDBYID VARCHAR(100),
	D_LASTMODIFIEDTIME DATE
);
