CREATE TABLE TUSER (
	C_USERID VARCHAR(100),
	C_USERNAME VARCHAR(100),
	C_USERCODE VARCHAR(100),
	C_ORGFULLCODE VARCHAR(100),
	C_MOBILE VARCHAR(100),
	C_EMAIL VARCHAR(100),
	C_ISLOCKED VARCHAR(100),
	C_ISDELETED VARCHAR(100),
	C_CREATEDBYID VARCHAR(100),
	D_CREATEDTIME VARCHAR(100),
	C_LASTMODIFIEDBYID VARCHAR(100),
	D_LASTMODIFIEDTIME VARCHAR(100),
	C_PASSWORD VARCHAR(100)
);

insert into TUSER(C_USERID, C_USERNAME) values('001','hmm');
